# Generated by Django 5.1.4 on 2024-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
