# Generated by Django 5.1.4 on 2024-12-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_berojgar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berojgar',
            old_name='skiil',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='skills',
            new_name='learn',
        ),
    ]
