# Generated by Django 5.1.4 on 2024-12-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_vacancy_vac'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('resume', models.ImageField(upload_to='')),
            ],
        ),
    ]
