# Generated by Django 5.1.4 on 2024-12-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_application_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='resume',
            new_name='photo',
        ),
    ]
