# Generated by Django 5.1.4 on 2024-12-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_resume_application_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='hrgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrname', models.CharField(max_length=20)),
                ('hremail', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=50)),
                ('hrpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
