# Generated by Django 5.1.4 on 2024-12-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_hrgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
