# Generated by Django 5.1.4 on 2024-12-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_company_application_mycompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mycompany',
            field=models.CharField(default='{{i.company}}', max_length=50),
        ),
    ]
