# Generated by Django 5.1.4 on 2024-12-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_application_mycompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mycompany',
            field=models.CharField(max_length=50),
        ),
    ]
