# Generated by Django 5.1.4 on 2024-12-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_application_mycompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='mycompany',
            new_name='company',
        ),
    ]
