# Generated by Django 5.1.4 on 2024-12-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_rename_mycompany_application_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.CharField(default='', max_length=50),
        ),
    ]
