# Generated by Django 5.1.4 on 2025-01-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_application_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrgroup',
            old_name='companyname',
            new_name='hrcompanyname',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vac',
            field=models.CharField(default='Not Mansion', max_length=10),
        ),
    ]
