# Generated by Django 5.1.4 on 2025-01-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_rename_companyname_hrgroup_hrcompanyname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrgroup',
            old_name='hrcompanyname',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='hrgroup',
            old_name='hremail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hrgroup',
            old_name='hrname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hrgroup',
            old_name='hrpassword',
            new_name='password',
        ),
    ]
