# Generated by Django 4.2.17 on 2025-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_rename_hrcompanyname_hrgroup_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.FileField(upload_to='media/image'),
        ),
    ]
