# Generated by Django 4.2.17 on 2025-01-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_application_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.FileField(upload_to='image'),
        ),
    ]
