# Generated by Django 4.2.17 on 2025-01-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_application_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.FileField(blank=True, upload_to='image'),
        ),
    ]
