# Generated by Django 4.2.17 on 2025-01-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_application_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=100)),
                ('reject', models.CharField(max_length=20)),
            ],
        ),
    ]
