# Generated by Django 4.2.17 on 2025-01-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_reject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reject',
            new_name='rejectapp',
        ),
    ]
