# Generated by Django 4.2.17 on 2025-01-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_rename_reject_rejectapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rejectapp',
            new_name='hrselection',
        ),
    ]
