# Generated by Django 4.2.17 on 2025-01-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_rename_rejectapp_hrselection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hrselection',
            new_name='hrreject',
        ),
    ]
