# Generated by Django 4.2.17 on 2025-01-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_rename_hrselection_hrreject'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrreject',
            name='company',
            field=models.CharField(default='applied', max_length=20),
        ),
    ]
