# Generated by Django 4.2.17 on 2025-01-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_hrreject_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrreject',
            name='company',
            field=models.CharField(max_length=20),
        ),
    ]
