# Generated by Django 4.2.17 on 2025-01-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_alter_hrreject_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apply',
            field=models.CharField(default='apply', max_length=100),
        ),
    ]
