# Generated by Django 4.2.17 on 2025-01-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_application_apply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hrreject',
        ),
    ]
